## Themes In This Talk

* Jupyter Notebooks - a great teaching tool.

* Teaching an Intro to Data Science course.
    * Fall 2023 - I taught an Intro to Data Science course at OIT.
    * Prerequisite: No Programming Experience - but all students had quite a bit.
    * Python Libraries Covered: Python Standard Library, NumPy, Pandas, Sci-Kit Learn.
    
* Using industry standard docstrings as a way to communicate expectations.

* Numpy

* Vectorizaton with Numpy

#### A Few Prerequisites

Comments: Any text after a $\#$ symbol is not 'seen' by the computer.  These are for humans reading the code.

$=$ versus $==$: In coding, $=$ is assignment and $==$ is what mathematicians think of when they write $=$.

# Numpy

Numpy (or *Numerical Python*) is a python array module (or library) that implements:

* Linear Algebra - Matrices, Tensors, Matrix Operations, etc.
* Vector Operations - Element-wise operations, array manipulations, etc. 

In [1]:
# This code tells python that we want to use the numpy module (library of objects, functions).
import numpy as np

### The N-Dimensional Array Object

The N-Dimensional Array (often abbreviated ndarray) is a multidimensional data structure or *container*.  The most common way to define an ndarray is to use the np.array function.

##### Example 1

In [62]:
#An ndarray
A = np.array([[1,2,3],[4,5,6]])

# In Jupyter Notebooks, the last line in a code cell is printed, provided it is something that can be printed.
A

array([[1, 2, 3],
       [4, 5, 6]])

The shape attribute tells us the shape of our array.  This will come in handy later.

In [63]:
A.shape

(2, 3)

The exercises are taken straight from my STAT 201 course.

##### NumPy Arrays Assignment: Exercise 1

Write code so that the following function performs the way that its docstring indicates.  **The first step, initializing a matrix of size (n,n) has been done for you**.

Example: times_table(3) should output a $3 \times 3$ array that looks like $\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}$.

times_table(5) should output a $5 \times 5$ array that looks like $\begin{pmatrix}
    1& 2& 3&4 &5\\
    2& 4& 6& 8& 10 \\
    3& 6& 9& 12& 15 \\
    4&8&12&16&20\\
    5&10&15&20&25
\end{pmatrix}$.

Hint: You will probably need to use a nested for-loop to do this.  Later in this chapter, when we get to **vectorization**, you will learn a way to do this without nested loops.

In [14]:
def times_table(n):
    """
    Parameters
    -----------
    n: positive integer
    
    Returns
    -----------
    ndarray of shape (n,n) that forms a times table
    """
    # This creates an n by n 0-matrix.
    A = np.zeros((n,n), dtype = 'int32')
    
    ###### Below was left blank - students had to produce something like this. #####
    
    for i in range(n):
        for j in range(n):
            A[i][j] = (i+1)*(j+1)
    return A

In [15]:
A = np.array(list(range(1,11))*10).reshape(10,-1)

if not np.allclose(times_table(3), np.array([1,2,3,2,4,6,3,6,9]).reshape(3,3)):
    print("Something is wrong with your code.")
elif not np.allclose(times_table(10), A.T * A):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

All tests passed.


# Numpy Vectorization



### What is Vectorization?

"*Vectorization* is the practice of replacing explicit loops with array expressions."  McKinney 2e, page 110

A simple example will illustrate.

##### Example 1

In [3]:
A = np.random.randint(1, 5, size = (10,))
A

array([2, 2, 3, 4, 2, 2, 1, 1, 2, 4])

**Problem**: Sum the numbers in $A$.

**Solution 1**: This is **Not** vectorization.

In [4]:
sum = 0
for x in A:
    sum = sum + x
sum

23

**Solution 2**: This **IS** vectorization.

In [5]:
A.sum()

23

$\Box$

### Why Vectorization?

"In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents." McKinney 2e, Page 110

##### Example 2

Now $A$ contains $90$,$000$,$000$ integers.

In [7]:
A = np.random.randint(1, 5, size = (90000000,))
A

array([4, 3, 2, ..., 2, 3, 3])

**Problem**: Sum the numbers in $A$.

**Solution 1**: This is **Not** vectorization.

In [10]:
sum = 0
for x in A:
    sum = sum + x
sum

224994130

**Solution 2**: This **IS** vectorization.

In [11]:
A.sum()

224994130

$\Box$

##### Example 3

We can perform arithmetic operations **element-wise** on Numpy arrays.

In [20]:
A = np.ones((10,))
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
B = np.array([2.0]*10)
B

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [23]:
# Addition
A+B

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [24]:
# Exponentiation
B**2

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

$\Box$

##### Vectorization Assignment: Exercise 1

Given a sequence of *observed values* $y_0,y_1,...,y_N$ and a sequence of *predicted values* $\hat{y_0},\hat{y_1},...,\hat{y_N}$, the *Mean Squared Error* is defined as $$\text{MSE} =\frac{1}{N}((y_0-\hat{y_0})^2+(y_1-\hat{y_1})^2+...+(y_N-\hat{y_N})^2)$$ 

Using summation notation this can be written as $$\text{MSE} = \frac{1}{N}\sum_{i=0}^N(y_i-\hat{y_i})^2$$

In this exercise, your job is to write a function that computes the MSE given an array of observed values and an array of observed values.  You should try to do this using vectorization (no explicit loops).

In [25]:
def MSE(observed_values, predicted_values):
    """
    Parameters
    -----------
    observed_values: ndarray of shape (N,)
    predicted_values: ndarray of shape (N,)
    
    Returns
    -----------
    float: the MSE of the parameters
    """
    

In [26]:
A1 = np.ones((10,))
B1 = np.array([2.0]*10)
A2 = np.array(range(1,11))
B2 = np.array(range(10,0,-1))

if MSE(A1, B1) != 1.0:
    print("Something is wrong with your code.")
elif MSE(A2,B2) != 33.0:
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

Something is wrong with your code.


$\Box$

### Mathematical Array Methods

NumPy provides many mathematical functions that can be applied to a whole array or along an axis.  

##### Example 4

In [8]:
A = np.array([[1]*3, [2]*3, [3]*3])
A

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

A.sum() adds all values in the array.

If we pass the argument axis $= 0$, we sum vertically.  

In [9]:
A.sum(axis = 0)

array([6, 6, 6])

If we pass the argument axis $= 1$, we sum horizontally.  

In [10]:
A.sum(axis = 1)

array([3, 6, 9])

$\Box$

##### Example 5

We can do the same with the mean.

In [13]:
A = np.array(range(1,21)).reshape(4,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
A.mean()

10.5

In [16]:
A.mean(axis = 0)

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [17]:
A.mean(axis = 1)

array([ 3.,  8., 13., 18.])

$\Box$

##### Vectorization Assignment: Exercise 2

In many Machine Learning applications, it is assumed that the data is *mean-centered*.  A mean-centered data set has the following property:

**The mean (or average) of each column is 0**.

-------------

As a sub-example, consider the following data set: $\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}$.  The mean of the colums are 2, 4, 6, respectively.  The mean-centered version of the data is then $\begin{pmatrix}
    1-2& 2-4& 3-6\\
    2-2& 4-4& 6-6 \\
    3-2& 6-4& 9-6 \\
\end{pmatrix}=\begin{pmatrix}
    -1& -2& -3\\
    0& 0& 0 \\
    1& 2& 3 \\
\end{pmatrix}$.  Notice that the mean (or average) of each column is 0.

-----------------

In this exercise, you are given a data set and it is your job to return the mean-centered version of this data set.

In [23]:
def mean_center(data):
    """
    Parameters
    -----------
    data: ndarray
    
    Returns
    -----------
    ndarray that is the mean-centered version of the data
    """
    ###### Below was left blank - students had to produce something like this. #####
    
    return data - data.mean(axis = 0)

In [24]:
D1 = np.array(range(20)).reshape(5,4)
D1_bar = np.array([[-8.0]*4, [-4.0]*4, [0.0]*4, [4.0]*4, [8.0]*4])
D2 = np.array([[1,5,2], [10,30,25], [-1,-3,0]])
D2_bar = np.array([[-2.333, -5.666, -7.0],[6.666, 19.333, 16.0],[-4.333,-13.666, -9.0]])

if not np.allclose(mean_center(D1), D1_bar, rtol=1e-7):
    print("Something is wrong with your code.")
elif not np.allclose(mean_center(D2), D2_bar, rtol=1e-3):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

All tests passed.


##### An Important Subtlety

Suppose that the data argument for the mean_center function was 

$\text{data} = \begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}$.  This array is two dimensional.

In [27]:
data = np.array([1,2,3,2,4,6,3,6,9]).reshape(3,3)
data

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

But, data.mean(axis = 0) produces a one-dimensional array. 

In [28]:
data.mean(axis = 0)

array([2., 4., 6.])

So, how does this not throw an error?

In [29]:
data - data.mean(axis = 0)

array([[-1., -2., -3.],
       [ 0.,  0.,  0.],
       [ 1.,  2.,  3.]])

Answer: *Broadcasting*.

$\Box$

##### Example 6: The Times Table Function

##### Solution 1: No Vectorization

In [30]:
def times_table(n):
    A = np.zeros((n,n), dtype = 'int32')
    for i in range(n):
        for j in range(n):
            A[i][j] = (i+1)*(j+1)
    return A

In [31]:
times_table(10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

##### Solution 2: Using Vectorization

Key observation: $\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}=\begin{pmatrix}
    1\cdot 1& 2\cdot 1& 3\cdot 1\\
    1 \cdot 2& 2\cdot 2& 3 \cdot 2 \\
    1 \cdot 3& 2\cdot 3& 3 \cdot 3 \\
\end{pmatrix}=\begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix} * \begin{pmatrix}
    1& 1& 1\\
    2& 2& 2 \\
    3& 3& 3 \\
\end{pmatrix}=\begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix} * \begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix}^T$

Solution:

In [39]:
def times_table(n):
    A = np.array(list(range(1,n+1))*n).reshape(n,n)
    return A*A.T

In [40]:
times_table(10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Breaking down the code, step by step:

In [34]:
n = 2

list(range(1,n+1))

[1, 2]

In [35]:
list(range(1,n+1))*n

[1, 2, 1, 2]

In [36]:
np.array(list(range(1,n+1))*n)

array([1, 2, 1, 2])

In [37]:
np.array(list(range(1,n+1))*n).reshape(n,n)

array([[1, 2],
       [1, 2]])

Lets compare the speed of these two solutions.

In [64]:
import time
n=1000

In [48]:
#Solution 1
start_time = time.time()
A = np.zeros((n,n), dtype = 'int32')
for i in range(n):
    for j in range(n):
        A[i][j] = (i+1)*(j+1)
print("--- %s seconds ---" % (time.time() - start_time))

--- 46.14466667175293 seconds ---


In [49]:
#Solution 2
start_time = time.time()
A = np.array(list(range(1,n+1))*n).reshape(n,n)
X = A*A.T
print("--- %s seconds ---" % (time.time() - start_time))

--- 8.277300119400024 seconds ---


$\Box$

## Applications

#### Distance Matrix

Given a dataset (with $n$ data points - rows) partitioned into *training* and *test* subsets, we create a matrix whose $ij$-entry is the *Euclidean* distance ($L^2$-norm) from data point $i$ to data point $j$.

$L^2$-Norm: $||\vec{x}-\vec{y}||_2 = \sqrt{(\vec{x}-\vec{y}) \cdot (\vec{x}-\vec{y})}$, where $\cdot$ is the standard inner-product (dot product).

##### Example 7: A Small Example

In [23]:
temp = np.ones((3,))
X = np.array([temp, 2*temp], dtype = 'int32')
X

array([[1, 1, 1],
       [2, 2, 2]])

In [24]:
Y = np.array([3*temp, 4*temp, 5*temp, 6*temp], dtype = 'int32')
Y

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

We need a way to compare each row in $X$ with each row in $Y$.

Enter the *repeat* method and *tile* function.

In [25]:
X1 = X.repeat(4, axis=0)
X1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
Y1 = np.tile(Y, (2,1))
Y1

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

Now, we build the Euclidean Norm using vector operations.

In [28]:
Z = X1 - Y1
Z

array([[-2, -2, -2],
       [-3, -3, -3],
       [-4, -4, -4],
       [-5, -5, -5],
       [-1, -1, -1],
       [-2, -2, -2],
       [-3, -3, -3],
       [-4, -4, -4]])

Recall that * is element-wise (not matrix) multiplication.

In [29]:
# dot product
Z*Z

array([[ 4,  4,  4],
       [ 9,  9,  9],
       [16, 16, 16],
       [25, 25, 25],
       [ 1,  1,  1],
       [ 4,  4,  4],
       [ 9,  9,  9],
       [16, 16, 16]])

Sum horizontally...

In [30]:
(Z*Z).sum(axis = 1)

array([12, 27, 48, 75,  3, 12, 27, 48])

...take the square root...

In [31]:
np.sqrt((Z*Z).sum(axis = 1))

array([3.46410162, 5.19615242, 6.92820323, 8.66025404, 1.73205081,
       3.46410162, 5.19615242, 6.92820323])

...and reshape into a $2\times 4$ distance matrix.

In [32]:
np.sqrt((Z*Z).sum(axis = 1)).reshape((2,4))

array([[3.46410162, 5.19615242, 6.92820323, 8.66025404],
       [1.73205081, 3.46410162, 5.19615242, 6.92820323]])

$\Box$

In general:

In [33]:
def distance_matrix(X, Y):
    """Compute the pairwise distance between rows of X and rows of Y

    Arguments
    ----------
    X: ndarray of size (N, D)
    Y: ndarray of size (M, D)
    
    Returns
    --------
    D: matrix of shape (N, M), each entry D[i,j] is the Euclidean distance between
    X[i] and Y[j].
    """
    
    N = X.shape[0]
    M = Y.shape[0]
    X1=X.repeat(M, axis=0)
    Y1=np.tile(Y, (N,1))
    Z=X1-Y1
    distance_matrix = np.sqrt((Z*Z).sum(axis=1).reshape((N,M)))
    return distance_matrix 

$\Box$

##### Confusion Matrix

The confusion matrix shows the number of *True Positives*, *True Negatives*, *False Positives*, and *False Negatives* for a classifier algorithm.

In [34]:
import pandas as pd

In [39]:
confusion_matrix = pd.DataFrame({'1': ['TP', 'FP'], '0': ['FN', 'TN']}, index = ['1', '0'])
confusion_matrix

1   0
1  TP  FN
0  FP  TN

##### Example 8

Suppose that a *machine learning* algorithm makes the following predictions $$\hat{Y} = \begin{pmatrix}
    1& 0& 1& 0& 0& 1& 0& 1& 1& 0\\
\end{pmatrix}$$ of the following true labels $$Y = \begin{pmatrix}
    1& 1& 0& 0& 0& 0& 1& 1& 1& 0\\
\end{pmatrix} \text{.}$$ 

In [40]:
#Y contains our correct answers
Y = np.array([1,0,1,0,0,1,0,1,1,0])
Y

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 0])

In [41]:
#Y_hat contains our predictions
Y_hat = np.array([1,1,0,0,0,0,1,1,1,0])
Y_hat

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 0])

##### True Positives (TP)

$\hat{Y}[i]=1 \text{ when } Y[i]=1$

In [51]:
TP = (Y*Y_hat).sum()
TP

3

##### True Negatives (TN)

$\hat{Y}[i]=0 \text{ when } Y[i]=0$

TN $=$ (TP $+$ TN) $-$ TP

In [52]:
TN = (Y == Y_hat).sum() - (Y*Y_hat).sum()
TN

3

##### False Positives

$\hat{Y}[i]=1 \text{ when } Y[i]=0$

We use the *bitwise* operator $\&$.

In [49]:
((Y_hat == 1) & (Y == 0))

array([False,  True, False, False, False, False,  True, False, False,
       False])

In [53]:
FP = ((Y_hat == 1) & (Y == 0)).sum()
FP

2

##### False Negatives

$\hat{Y}[i]=0 \text{ when } Y[i]=1$

In [58]:
(Y_hat == 0)&(Y == 1)

array([False, False,  True, False, False,  True, False, False, False,
       False])

In [60]:
FN = ((Y_hat == 0)&(Y == 1)).sum()
FN

2

$\Box$

##### Confusion Matrix

Recall that 

$\hat{Y} = \begin{pmatrix}
    1& 0& 1& 0& 0& 1& 0& 1& 1& 0\\
\end{pmatrix}$

and

$Y = \begin{pmatrix}
    1& 1& 0& 0& 0& 0& 1& 1& 1& 0\\
\end{pmatrix}$.

In [61]:
confusion_matrix = pd.DataFrame({'1': [TP, FP], '0': [FN, TN]}, index = ['1', '0'])
confusion_matrix

1  0
1  3  2
0  2  3

$\Box$

### Thanks for Coming to My Talk!!!